// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZEUgLpoQVMiNq6-h82k6lRqDSPeXA6Sw',
    appId: '1:363942247079:web:04c62198a57fd40f2bb982',
    messagingSenderId: '363942247079',
    projectId: 'geomark-attendance-app',
    authDomain: 'geomark-attendance-app.firebaseapp.com',
    storageBucket: 'geomark-attendance-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYm4myVug6bE6TZjMjqTQlWOvN5XjTwBs',
    appId: '1:363942247079:android:7b57647d423385722bb982',
    messagingSenderId: '363942247079',
    projectId: 'geomark-attendance-app',
    storageBucket: 'geomark-attendance-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6m5h_0o-AlMbcp7DqfUIAPUnz1-UfCZo',
    appId: '1:363942247079:ios:337a8d3da1e4a09c2bb982',
    messagingSenderId: '363942247079',
    projectId: 'geomark-attendance-app',
    storageBucket: 'geomark-attendance-app.appspot.com',
    iosBundleId: 'com.example.geomark',
  );
}
